fixed missing bracket.

diff --git a/.github/workflows/Generate_Register_Files.yml b/.github/workflows/Generate_Register_Files.yml
--- a/.github/workflows/Generate_Register_Files.yml
+++ b/.github/workflows/Generate_Register_Files.yml
@@ -127,31 +127,31 @@ jobs:
           readarray -d " " -t cmdarr <<< "$command"
 
           # Only run if the first argument is the command
-          if [[ "${cmdarr[0]" =~ "test" ]]; then
+          if [[ "${cmdarr[0]}" =~ "test" ]]; then
             # Generate all register files if you only run the command with no part specified
-          #   if [[ ${#cmdarr[@]} == 1 ]]; then
-          #     part="all"
-          #   else
-          #     # Capitalize part designation argument
-          #     part="${cmdarr[1]^^}"
+            if [[ ${#cmdarr[@]} == 1 ]]; then
+              part="all"
+            else
+              # Capitalize part designation argument
+              part="${cmdarr[1]^^}"
 
-          #     # Confirm second argument is the part designation
-          #     if [[ ${DIE_TO_CHIP_NAMES[$part]+_} ]]; then
-          #       chip_name=${DIE_TO_CHIP_NAMES[$part]}
-          #       die_name=$part
+              # Confirm second argument is the part designation
+              if [[ ${DIE_TO_CHIP_NAMES[$part]+_} ]]; then
+                chip_name=${DIE_TO_CHIP_NAMES[$part]}
+                die_name=$part
 
-          #     elif [[ ${CHIP_TO_DIE_NAMES[$part]+_} ]]; then
-          #       chip_name=$part
-          #       die_name=${CHIP_TO_DIE_NAMES[$part]}
+              elif [[ ${CHIP_TO_DIE_NAMES[$part]+_} ]]; then
+                chip_name=$part
+                die_name=${CHIP_TO_DIE_NAMES[$part]}
 
-          #     else
-          #       echo -e "[\e[0;31mERROR\e[0m] Unknown part number."
-          #       exit 1
-          #     fi
-          #   fi
-          # else
+              else
+                echo -e "[\e[0;31mERROR\e[0m] Unknown part number."
+                exit 1
+              fi
+            fi
+          else
             echo -e "[\e[0;31mERROR\e[0m] Incorrect command. Please start comment with: \/generate\-register\-files."
-          #   exit 1
+            exit 1
           fi
 
           # Generate all register files if part not specified.
