Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -425,26 +425,26 @@ jobs:
 
           CHECK_FAIL=0
           set +e
-          for updated_reg_file in "${!DIFF_PR_REG_TO_SVD_REG_LIST[@]}"
+          for affected_pr_reg_file in "${!DIFF_PR_REG_TO_SVD_REG_LIST[@]}"
           do
             # Make sure the generated register file exists by checking if there's a same file name register file that was generated by the SVD scripts. 
             # If it doesn't, you've added a new register file. Please contact the developers.
-            if [[ -f ${DIFF_PR_REG_TO_SVD_REG_LIST[$updated_reg_file]} ]]; then
-              echo -e "[\e[0;37mCOMPARING\e[0m] Changed: \e[1;33m$updated_reg_file  \e[0m==>  Generated: \e[0;32m${DIFF_PR_REG_TO_SVD_REG_LIST[$updated_reg_file]}"
-              diff -u $updated_reg_file ${DIFF_PR_REG_TO_SVD_REG_LIST[$updated_reg_file]}
-              check_reg_diff=$?
+            if [[ -f ${DIFF_PR_REG_TO_SVD_REG_LIST[$affected_pr_reg_file]} ]]; then
+              echo -e "[\e[0;37mCOMPARING\e[0m] Changed: \e[1;33m$affected_pr_reg_file  \e[0m==>  Generated: \e[0;32m${DIFF_PR_REG_TO_SVD_REG_LIST[$affected_pr_reg_file]}"
+              diff -u $affected_pr_reg_file ${DIFF_PR_REG_TO_SVD_REG_LIST[$affected_pr_reg_file]}
+              check_reg_diff_return=$?
             
               # Find all files linked to
-              periph=${updated_reg_file##*/}
+              periph=${affected_pr_reg_file##*/}
               periph=${periph%_regs.h}
-              chip_name=${updated_reg_file#*/Maxim/}
+              chip_name=${affected_pr_reg_file#*/Maxim/}
               chip_name=${chip_name%%/*}
-              linked_reg_files_to_current_svd_file=$(find_linked_register_files ${REGISTER_SVD_FILE_LIST[${updated_reg_file#./*/}]} $periph $chip_name .)
+              linked_reg_files_to_current_svd_file=$(find_linked_register_files ${REGISTER_SVD_FILE_LIST[${affected_pr_reg_file#./*/}]} $periph $chip_name .)
 
               # Check return for any differences and if there are any linked register files to update
-              if [[ $check_reg_diff != 0 || -n $linked_reg_files_to_current_svd_file ]]; then
-                if [[ $check_reg_diff != 0 ]]; then
-                  echo -e "[\e[0;31mERROR\e[0m] \e[1;33m${updated_reg_file#./*/} \e[0mdoes not match with corresponding SVD File."
+              if [[ $check_reg_diff_return != 0 || -n $linked_reg_files_to_current_svd_file ]]; then
+                if [[ $check_reg_diff_return != 0 ]]; then
+                  echo -e "[\e[0;31mERROR\e[0m] \e[1;33m${affected_pr_reg_file#./*/} \e[0mdoes not match with corresponding SVD File."
                 else
                   echo -e "[\e[0;31mERROR\e[0m] Register File and corresponding Peripheral SVD File are synced, but there are other parts' register files dependent on this Peripheral SVD File."
                 fi
@@ -452,15 +452,15 @@ jobs:
                 # DO NOT CHANGE register file if there is no corresponding SVD file. That means the register file is deprecated, and
                 # non-deprecated version should be updated
                 # REGISTER_SVD_FILE_LIST paths relative to script location being in the msdk repo but running pwd shows it's outside of msdk and msdk-internal repos.
-                if [[ -f "./${{ env.MSDK_DIR }}/${REGISTER_SVD_FILE_LIST[${updated_reg_file#./*/}]}" ]]; then
-                  if [[ $check_reg_diff != 0 ]]; then 
+                if [[ -f "./${{ env.MSDK_DIR }}/${REGISTER_SVD_FILE_LIST[${affected_pr_reg_file#./*/}]}" ]]; then
+                  if [[ $check_reg_diff_return != 0 ]]; then 
                     echo -e "        Please make sure both register file and SVD file are synced:"  
-                    echo -e "            \e[1;31m${updated_reg_file#./*/}"
-                    echo -e "            \e[1;31m${REGISTER_SVD_FILE_LIST[${updated_reg_file#./*/}]}"
+                    echo -e "            \e[1;31m${affected_pr_reg_file#./*/}"
+                    echo -e "            \e[1;31m${REGISTER_SVD_FILE_LIST[${affected_pr_reg_file#./*/}]}"
                   fi
 
                   if [[ -n $linked_reg_files_to_current_svd_file ]]; then
-                    echo -e "        Please sync up all other register files linked to the peripheral SVD file - (${REGISTER_SVD_FILE_LIST[${updated_reg_file#./*/}]}):"
+                    echo -e "        Please sync up all other register files linked to the peripheral SVD file - (${REGISTER_SVD_FILE_LIST[${affected_pr_reg_file#./*/}]}):"
                     
                     for change_linked_reg_files in $linked_reg_files_to_current_svd_file
                     do
@@ -480,16 +480,16 @@ jobs:
                 echo -e "[\e[0;32mVERIFIED\e[0m] Register File and Corresponding Peripheral SVD File are synced.\n"
               fi
             else
-              echo -e "[\e[0;37mVERIFYING\e[0m] Changed: \e[1;33m${updated_reg_file#./*/}."
+              echo -e "[\e[0;37mVERIFYING\e[0m] Changed: \e[1;33m${affected_pr_reg_file#./*/}."
               
               CHECK_FAIL=1
-              check_for_at_deprecated=$(grep -rl "@deprecated" $updated_reg_file)
+              check_for_at_deprecated=$(grep -rl "@deprecated" $affected_pr_reg_file)
               if [[ -n $check_for_at_deprecated ]]; then
                 # Exception for deprecated register files.
                 echo -e "[\e[0;31mERROR\e[0m] DO NOT UPDATE. This file is deprecated. Please contact ADI developers for more support.\n\n"
               else
                 # Exception for entirely new register files.
-                echo -e "[\e[0;31mERROR\e[0m] Could not find ${REGISTER_SVD_FILE_LIST[${updated_reg_file#./*/}]} for ${updated_reg_file#./*/}. Please add the correct SVD file. PLease contact the developers if you are adding a new register file.\n\n"
+                echo -e "[\e[0;31mERROR\e[0m] Could not find ${REGISTER_SVD_FILE_LIST[${affected_pr_reg_file#./*/}]} for ${affected_pr_reg_file#./*/}. Please add the correct SVD file. PLease contact the developers if you are adding a new register file.\n\n"
               fi
             fi
           done
